#!/bin/bash
# Quick reference for running SentinelAI with full event flow logging

set -e

echo "🎬 SentinelAI Startup Guide"
echo "===================================================================="
echo ""
echo "This script starts all components with event flow logging enabled."
echo ""
echo "Prerequisites:"
echo "  - Python 3.10+ with pip (backend + worker)"
echo "  - Node.js 16+ with npm (frontend)"
echo "  - Test videos in test_videos/school/ (for demo)"
echo ""
echo "===================================================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Startup order
echo -e "${BLUE}Step 1: Starting Backend (FastAPI)${NC}"
echo "Command: cd backend && uvicorn main:app --reload --port 8000"
echo ""
echo "Expected logs:"
echo "  ✓ [EVENT_RX_ACCEPT] - Backend receives event"
echo "  ✓ [WS_BROADCAST_START] - WebSocket broadcast begins"
echo "  ✓ [WS_SEND_OK] - Client receives alert"
echo ""
echo -e "${YELLOW}Run in Terminal 1:${NC}"
echo "  cd backend"
echo "  python -m pip install -r requirements.txt  # if needed"
echo "  uvicorn main:app --reload --port 8000"
echo ""
echo ">>> Press Enter after backend is running (will see 'Application startup complete')"
read

echo ""
echo -e "${BLUE}Step 2: Starting Dashboard (Next.js)${NC}"
echo "Command: cd dashboard && npm run dev"
echo ""
echo "Expected logs:"
echo "  ✓ [WS_CONNECTED] ready for alerts - Ready to receive WebSocket messages"
echo "  ✓ [WS_MESSAGE_RX] - Frontend receives alert from WebSocket"
echo "  ✓ [ALERT_DISPLAYED] - Alert popup shown"
echo ""
echo -e "${YELLOW}Run in Terminal 2:${NC}"
echo "  cd dashboard"
echo "  npm install  # if needed"
echo "  npm run dev"
echo ""
echo ">>> Press Enter after dashboard starts (will see 'ready - started server on')"
read

echo ""
echo -e "${BLUE}Step 3: Testing Event Flow${NC}"
echo ""
echo -e "${GREEN}Option A: Debug Ping (No worker needed)${NC}"
echo "  - Tests event flow without real detection"
echo "  - Run in Terminal 3:"
echo ""
echo "    curl http://localhost:8000/api/debug/ping"
echo ""
echo "  - Check browser console for [WS_MESSAGE_RX]"
echo "  - Watch for 'Debug ping received' alert in dashboard"
echo ""
echo ""
echo -e "${GREEN}Option B: Full Test Suite${NC}"
echo "  - Comprehensive event flow validation"
echo "  - Run in Terminal 3:"
echo ""
echo "    python scripts/test_event_flow.py"
echo ""
echo "  - Will test: HTTP endpoint, WebSocket, schema validation"
echo "  - Look for: 'All tests passed ✓'"
echo ""
echo ""
echo -e "${GREEN}Option C: Real Detection with Worker${NC}"
echo "  - Requires test videos in test_videos/school/"
echo "  - Run in Terminal 3:"
echo ""
echo "    cd ai_worker"
echo "    python test_worker.py school_ground ../test_videos/school/demo.mp4"
echo ""
echo "  - Will log [EVENT_EMIT] when weapon/crowd detected"
echo ""

echo ""
echo "===================================================================="
echo "📊 Event Flow Logging Locations"
echo "===================================================================="
echo ""
echo "Backend Logs (Terminal 1 running FastAPI):"
echo "  • [EVENT_RX_ACCEPT] - Event received from worker"
echo "  • [EVENT_INCIDENT_DETECTED] - Event identified as incident"
echo "  • [BROADCAST_QUEUED] - Alert queued for WebSocket"
echo "  • [WS_BROADCAST_START] - Starting to send to clients"
echo "  • [WS_SEND_OK] - Client received alert"
echo ""
echo "Worker Logs (Terminal 3 if running worker):"
echo "  • [EVENT_EMIT] - Event detected and ready to send"
echo "  • [EVENT_DELIVERY_OK] - Backend received event (HTTP 200)"
echo "  • [EVENT_SUPPRESSED] - Event filtered by cooldown"
echo ""
echo "Frontend Logs (Browser Developer Tools Console, F12):"
echo "  • [WS_CONNECT_ATTEMPT] - Connecting to WebSocket"
echo "  • [WS_CONNECTED] - Connected and ready"
echo "  • [WS_MESSAGE_RX] - Received message from server"
echo "  • [ALERT_PROCESS] - Processing alert for display"
echo "  • [ALERT_DISPLAYED] - Alert popup shown"
echo ""

echo ""
echo "===================================================================="
echo "🎯 Quick Debugging"
echo "===================================================================="
echo ""
echo "1. Backend not responding:"
echo "   curl http://localhost:8000/api/stats"
echo ""
echo "2. Test WebSocket manually:"
echo "   wscat -c ws://localhost:8000/ws/alerts"
echo ""
echo "3. Send test event:"
echo "   python scripts/test_event_flow.py"
echo ""
echo "4. Check log files:"
echo "   # Find all event flow related logs"
echo "   grep '\\[EVENT' backend.log"
echo "   grep '\\[WS_' backend.log"
echo ""
echo "5. Browser console (F12):"
echo "   Filter by '[WS_' to see all WebSocket activity in frontend"
echo ""

echo ""
echo "====================================================================="
echo "✅ System Ready!"
echo "====================================================================="
echo ""
echo "Next steps:"
echo "  1. Open http://localhost:3000 in browser"
echo "  2. Open DevTools (F12) → Console tab"
echo "  3. Run debug ping or worker in Terminal 3"
echo "  4. Watch logs appear in real-time across all terminals"
echo "  5. See alert popup in dashboard when event detected"
echo ""
